; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

; Generated by VC++ for Common Language Runtime
.file "C:\nobu7_tool_retsuden_editor\RetsudenEditor\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
