; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

; Generated by VC++ for Common Language Runtime
.file "G:\repogitory_jp\nobu7_yool_retsuden_editor\RetsudenEditor\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
